[WIP]リファクタリング(2021/03/17)
hideki0145/reserven pull request #7
Opened 2021-03-19 02:15 UTC by MahiroTakeshitaPrivate

リファクタリングを実施する。

2021-03-19 02:16 UTC, hideki0145 reviewed
現状の修正箇所については問題ありません。
引き続き実装をお願いします。

2021-03-22 04:17 UTC, hideki0145 commented on app/controllers/application_controller.rb
> +  def log_out
log_outメソッドをApplicationControllerに記述するのであれば、release_remember_cookiesメソッドも同時に記述しないと今後SessionsController以外からlog_outメソッドが呼び出しされた場合にエラーとなります。

1. log_outメソッドをSessionsControllerに記述する
2. release_remember_cookiesメソッドをApplicationControllerに記述する

上記[1.][2.]どちらも利点があるかと思いますが、一度記述場所を考えてみてください。

2021-03-22 04:18 UTC, hideki0145 requested changes
log_outメソッド関連の記述場所について指摘があります。
確認をお願いします。

2021-03-22 05:29 UTC, MahiroTakeshitaPrivate commented on app/controllers/application_controller.rb
> +  def log_out
[2.]にて修正を行いました。再レビュー願います。

2021-03-22 05:37 UTC, hideki0145 reviewed
現状の修正箇所については問題ありません。
引き続き実装をお願いします。

2021-03-22 05:42 UTC, hideki0145 approved these changes

2021-03-23 07:16 UTC, hideki0145 approved these changes
プログラムの改善を確認しました。
masterブランチへのマージをお願いします。

2021-03-31 02:01 UTC, merged